version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: student_management
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
